import React from "react";
import { Link } from "react-router-dom";

import Header from "../components/Header";
import Footer from "../components/Footer";

export const CookiesPage = () => (
  <div>
    <Header />
    <div className="container">
      <h1>Cookies Page</h1>
      <h2> What are cookies?</h2>
      <p>
        Cookies are small text files that websites can store on your browser to
        help with the functionality of the site and provide additional services,
        such as shopping carts, advertising and security.
      </p>
      <h2> What cookies are used on this website? </h2>
      <p>
        When a user logs in with their Google profile, Google stores cookies on
        the browser to keep a track of authentication and data usage. Spyced
        Concepts does not collect any personal information, or store any of it's
        own cookies on this demo website.
      </p>
      <h2> Who is responsible for the cookies on this website?</h2>
      <p>
        All the cookies stores on this website are generated by Google and are
        directly related to the use of your Google account to sign in and use
        the demo services.
      </p>
      <h2> What if I don't want to use cookies.</h2>
      <p>
        To get rid of any cookies that have been stored whilst using this site,
        you can search for cookie management relating to your browser, and
        follow instructions on deleting cookies for particular websites.
      </p>
      <p>
        If you don't wish Google to store cookies when you use their login
        systems, then you can choose alternative ways to login to many sites. At
        the moment, however, this website only accepts logging in via your
        Google profile, if you have one.d
      </p>
    </div>
    <Footer />
  </div>
);

export default CookiesPage;
