import React from "react";
import Header from "../components/Header";
import Footer from "../components/Footer";

export const PrivacyPage = () => (
  <div>
    <Header />
    <div className="container">
      <h1>Privacy</h1>
      <h2>What are the rules governing this sites privacy policy? </h2>
      <p>
        Although some of the services used by this demo app are owned by Google,
        the governing laws covering data and privacy on this site are those of
        England and Wales, in particular the Uk GDPR regulations.
      </p>
      <h2>What private data does this site hold </h2>
      <p>
        The only data this site gathers is the information which users
        volutarily enter when they add, edit or delete expenses. None of this
        data has a direct refernece to the users personal details, only a token
        generated by Google to manage the users logged in status.
      </p>
      <p>
        This sites authorization process is managed entirely by Google's
        Firebase authentication system. All directly identifiable personal
        information is recorded and process on Google's systems, via the user
        own Google account.
      </p>
      <h2>How do I get my data deleted?</h2>
      <p>
        As this is a demo site, the databases are frequently cleared and all
        records removed. However, if a user specifically wants their data
        deleted, they can contact Spyced Concepts with details of at least 2
        expenses recorded in the system, and our administrator will delete all
        the information, including the google reference. All data removed is
        unrecoverable.
      </p>
      <h2>How long do you hold data for?</h2>
      <p>
        As this is a demo site, data is frequently deleted, and may be deleted
        without warning. This site offers no guarantees of data persistence.
      </p>
      <h2>Who do I contact about privacy concerns?</h2>
      <p>
        You can drop an email to{" "}
        <a href="mailto:datacontroller@spycedconcepts.uk ">
          datacontroller@spycedconcepts.uk
        </a>
        to ask any questions or raise any security concerns with us.
      </p>
    </div>
    <Footer />
  </div>
);

export default PrivacyPage;
